-- ==============================================================================
-- Expression Detection → Activity Timeline Bridge
-- Run this ONCE in your Supabase SQL Editor.
--
-- When the Smart Mirror backend INSERTs a row into mirror_reactions
-- (e.g. expression detection fires: sad, fearful, angry, smile),
-- this trigger automatically logs it into the activity_events table
-- so it appears live in the Caregiver App's Activity Timeline.
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.log_reaction_as_activity()
RETURNS TRIGGER AS $$
DECLARE
  evt_severity TEXT;
  evt_type     TEXT;
BEGIN
  -- Map reaction_type to severity and event_type
  IF NEW.reaction_type IN ('sos', 'help', 'cry', 'cried', 'fearful', 'angry', 'disgusted') THEN
    evt_severity := 'warning';
    evt_type     := 'expression_alert';
  ELSIF NEW.reaction_type IN ('sad', 'unhappy') THEN
    evt_severity := 'warning';
    evt_type     := 'expression';
  ELSE
    -- smile, laugh, wave, viewed, neutral, happy, surprised, etc.
    evt_severity := 'info';
    evt_type     := 'expression';
  END IF;

  INSERT INTO public.activity_events (
    elderly_id,
    event_type,
    description,
    severity,
    source_table,
    source_id,
    occurred_at
  ) VALUES (
    NEW.elderly_id,
    evt_type,
    -- Use the human-friendly message already generated by the
    -- format_mirror_reaction_message trigger (if present), 
    -- otherwise fall back to a generic label.
    COALESCE(NULLIF(NEW.message, ''), 'Mirror reaction: ' || NEW.reaction_type),
    evt_severity,
    'mirror_reactions',
    NEW.id,
    NEW.created_at
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if re-running this script
DROP TRIGGER IF EXISTS on_reaction_log_activity ON public.mirror_reactions;

-- Fire AFTER INSERT so the format_mirror_reaction_message BEFORE trigger
-- has already populated NEW.message before we copy it.
CREATE TRIGGER on_reaction_log_activity
AFTER INSERT ON public.mirror_reactions
FOR EACH ROW EXECUTE FUNCTION public.log_reaction_as_activity();
